name: ci

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3    #github action
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: check files
        uses: actions/checkout@v4 
        
      - name: list files 
        run: ls -l

      - name: Run Docker Image
        uses: hoverkraft-tech/compose-action@v1.5.1

      - name: push image
        run: docker push ayaz000/wordpress500:latest
    
        